name: Create Release

on: 
    push: 
        branches: 
            - main
jobs:
    release-on-merge:
        runs-on: ubuntu-latest
        permissions: 
            contents: write
        env:
            GITHUB_TOKEN: ${{ secrets.GO_RELEASER_GITHUB_TOKEN }}
        steps:
            - name: Checkout code
              uses: actions/checkout@v2
            - name: create release
              uses: actions/create-release@v1
              with:
                tag_name: ${{ github.ref }}
                release_name: Release ${{ github.ref }}
                draft: false
                prerelease: false